### ISSUE TITLE
I imported base.scs and it went wrong.

### ISSUE THREAD

**Issue by 1761792934** [simon50keda/ConverterPIXWrapper#1]
### ### Traceback (most recent call last):
  File "D:\steam-Game\steamapps\common\Blender\2.81\scripts\addons\io_converter_pix_wrapper\__init__.py", line 702, in execute
    textures_to_base=self.textures_to_base)
  File "D:\steam-Game\steamapps\common\Blender\2.81\scripts\modules\bpy\ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: 错误: Traceback (most recent call last):
  File "D:\steam-Game\steamapps\common\Blender\2.81\scripts\addons\io_converter_pix_wrapper\__init__.py", line 376, in invoke
    if not self.model_browser_data.is_subpath_valid():
  File "D:\steam-Game\steamapps\common\Blender\2.81\scripts\addons\io_converter_pix_wrapper\__init__.py", line 189, in is_subpath_valid
    dirs, files = get_archive_listdir(archive_paths, self.current_subpath)
  File "D:\steam-Game\steamapps\common\Blender\2.81\scripts\addons\io_converter_pix_wrapper\__init__.py", line 142, in get_archive_listdir
    retcode, stdout = run_converter_pix(args)
  File "D:\steam-Game\steamapps\common\Blender\2.81\scripts\addons\io_converter_pix_wrapper\__init__.py", line 108, in run_converter_pix
    result = subprocess.run(final_command, stdout=subprocess.PIPE)
  File "D:\steam-Game\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\steam-Game\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\steam-Game\steamapps\common\Blender\2.81\python\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

location: D:\steam-Game\steamapps\common\Blender\2.81\scripts\modules\bpy\ops.py:199

location: <unknown location>:-1

**Comment by simon50keda** [comment]
Hm, could you translate the non-english part of error? Looks like there is some Windows implementation problems.

**Comment by 5766pav** [comment]
![Blender 08 07 2023 22_53_14](https://github.com/simon50keda/ConverterPIXWrapper/assets/139046882/5f99d93f-2385-473b-982c-71d73c16fe30)
Вы можете помочь в решении проблемы

**Comment by simon50keda** [comment]
Old issue, please retry with: https://github.com/simon50keda/ConverterPIXWrapper/releases/tag/v2.3
If problem persist, reopen the issue.

**Comment by martincaravello** [comment]
Hi, I'm having the same problem. I downloaded what you sent, but it didn't work. What can I do?

**Comment by martincaravello** [comment]
Python: Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\addons\io_converter_pix_wrapper\__init__.py", line 707, in execute
    bpy.ops.converter_pix_wrapper.list_and_import("INVOKE_DEFAULT",
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\addons\io_converter_pix_wrapper\__init__.py", line 384, in invoke
    if not self.model_browser_data.is_subpath_valid():
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\addons\io_converter_pix_wrapper\__init__.py", line 197, in is_subpath_valid
    dirs, files = get_archive_listdir(archive_paths, self.current_subpath)
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\addons\io_converter_pix_wrapper\__init__.py", line 149, in get_archive_listdir
    retcode, stdout = run_converter_pix(args)
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\addons\io_converter_pix_wrapper\__init__.py", line 114, in run_converter_pix
    result = subprocess.run(final_command, stdout=subprocess.PIPE)
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
Ubicación: D:\SteamLibrary\steamapps\common\Blender\3.6\scripts\modules\bpy\ops.py:111
