### ISSUE TITLE
Console repeatedly reported `TypeError: 'NoneType' object is not callable` at every drawn frame

### ISSUE THREAD

**Issue by avengerx** [simon50keda/ConverterPIXWrapper#11]
When I finally could import a model into Blender, the console is repeatedly reporting as I move the viewport around (so, every draw of the model) the following block:

```
Traceback (most recent call last):
  File "C:\Users\avenger\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scs_tools\internals\open_gl\core.py", line 460, in draw_custom_3d_elements
    bgl.glEnable(bgl.GL_DEPTH_TEST)
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "C:\Users\avenger\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scs_tools\internals\open_gl\core.py", line 485, in draw_custom_2d_elements
    _draw_3dview_report(window, area, region)
  File "C:\Users\avenger\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scs_tools\internals\open_gl\core.py", line 142, in _draw_3dview_report
    bgl.glEnable(bgl.GL_BLEND)
TypeError: 'NoneType' object is not callable
```

I looked for these files in the repository but it seems there's only a `init.py`; I'm not very keen in Blender extensions but I assume the actual extension sources are not tracked in this repository, so I couldn't point the respective source files' lines.

According to this Blender-exchange answer, a path check should happen in the script logic to avoid these errors (or warnings, not sure it breaks anything at all) : [Rendering through a python script and receive an Error: "TypeError: 'NoneType' object is not callable](https://blender.stackexchange.com/questions/227653/rendering-through-a-python-script-and-receive-an-error-typeerror-nonetype-o)

**EDIT:** Of course I didn't find the `core.py` file, this issue is related to the SCS Tools not this extension.

**Comment by simon50keda** [comment]
Blender 4.X is not supported. The issue above is one of which why it's not.

**Comment by avengerx** [comment]
That's not related to ConverterPIXWrapper, right? It's to SCS Tools instead, and perhaps this should be stated in modding.scssoft.com?
